// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHyAvuH6B_JCGOgsI_Wy4Q3WAcofOVD4k',
    appId: '1:455492802356:web:5a4aeb62281d26ea1a3761',
    messagingSenderId: '455492802356',
    projectId: 'ezsave-fb14f',
    authDomain: 'ezsave-fb14f.firebaseapp.com',
    storageBucket: 'ezsave-fb14f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2gvwYdsb9wbr6oznT2pKQMfVANtRMg3k',
    appId: '1:455492802356:android:51e58119a3bf52b61a3761',
    messagingSenderId: '455492802356',
    projectId: 'ezsave-fb14f',
    storageBucket: 'ezsave-fb14f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1W4xkdIooW9riKAucAYKdWUhKeHF0IJc',
    appId: '1:455492802356:ios:787234ca6c41ae221a3761',
    messagingSenderId: '455492802356',
    projectId: 'ezsave-fb14f',
    storageBucket: 'ezsave-fb14f.firebasestorage.app',
    iosClientId: '455492802356-hj0mlgmo20lo0a08sj3veoejprf5aj9g.apps.googleusercontent.com',
    iosBundleId: 'com.digitalsauce.ezSave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHyAvuH6B_JCGOgsI_Wy4Q3WAcofOVD4k',
    appId: '1:455492802356:web:2f8fed6cf611a1741a3761',
    messagingSenderId: '455492802356',
    projectId: 'ezsave-fb14f',
    authDomain: 'ezsave-fb14f.firebaseapp.com',
    storageBucket: 'ezsave-fb14f.firebasestorage.app',
  );
}
